module bitonic_sorter_16 (
    input clk_i,
    input resetn_i,
    input descend_i,    //if high sort G to L
    input valid_i,
    //input values
    input [31:0] val_1_i,
    input [31:0] val_2_i,
    input [31:0] val_3_i,
    input [31:0] val_4_i,
    input [31:0] val_5_i,
    input [31:0] val_6_i,
    input [31:0] val_7_i,
    input [31:0] val_8_i,
    input [31:0] val_9_i,
    input [31:0] val_10_i,
    input [31:0] val_11_i,
    input [31:0] val_12_i,
    input [31:0] val_13_i,
    input [31:0] val_14_i,
    input [31:0] val_15_i,
    input [31:0] val_16_i,
    //output values
    output valid_o,
    output descend_o,
    output [31:0] val_1_o,
    output [31:0] val_2_o,
    output [31:0] val_3_o,
    output [31:0] val_4_o,
    output [31:0] val_5_o,
    output [31:0] val_6_o,
    output [31:0] val_7_o,
    output [31:0] val_8_o,
    output [31:0] val_9_o,
    output [31:0] val_10_o,
    output [31:0] val_11_o,
    output [31:0] val_12_o,
    output [31:0] val_13_o,
    output [31:0] val_14_o,
    output [31:0] val_15_o,
    output [31:0] val_16_o
);

    logic [31:0] first_stage_out_l [16];
    logic [31:0] second_stage_out_l [16];
    logic [31:0] third_stage_out_l [16];
    logic first_stage_valid_l, second_stage_valid_l, third_stage_valid_l;
    logic first_stage_descend_l, second_stage_descend_l, third_stage_descend_l;
    
    bitonic_sorter_first_stage first_stage (
    .clk_i(clk_i),
    .resetn_i(resetn_i),
    .descend_i(descend_i),
    .valid_i(valid_i),
    .val_1_i(val_1_i),
    .val_2_i(val_2_i),
    .val_3_i(val_3_i),
    .val_4_i(val_4_i),
    .val_5_i(val_5_i),
    .val_6_i(val_6_i),
    .val_7_i(val_7_i),
    .val_8_i(val_8_i),
    .val_9_i(val_9_i),
    .val_10_i(val_10_i),
    .val_11_i(val_11_i),
    .val_12_i(val_12_i),
    .val_13_i(val_13_i),
    .val_14_i(val_14_i),
    .val_15_i(val_15_i),
    .val_16_i(val_16_i),
    //Outputs
    .valid_o(first_stage_valid_l),
    .descend_o(first_stage_descend_l),
    .val_1_o(first_stage_out_l[0]),
    .val_2_o(first_stage_out_l[1]),
    .val_3_o(first_stage_out_l[2]),
    .val_4_o(first_stage_out_l[3]),
    .val_5_o(first_stage_out_l[4]),
    .val_6_o(first_stage_out_l[5]),
    .val_7_o(first_stage_out_l[6]),
    .val_8_o(first_stage_out_l[7]),
    .val_9_o(first_stage_out_l[8]),
    .val_10_o(first_stage_out_l[9]),
    .val_11_o(first_stage_out_l[10]),
    .val_12_o(first_stage_out_l[11]),
    .val_13_o(first_stage_out_l[12]),
    .val_14_o(first_stage_out_l[13]),
    .val_15_o(first_stage_out_l[14]),
    .val_16_o(first_stage_out_l[15])
);

bitonic_sorter_second_stage second_stage (
    .clk_i(clk_i),
    .resetn_i(resetn_i),
    .descend_i(first_stage_descend_l),
    .valid_i(first_stage_valid_l),
    .val_1_i(first_stage_out_l[0]),
    .val_2_i(first_stage_out_l[1]),
    .val_3_i(first_stage_out_l[2]),
    .val_4_i(first_stage_out_l[3]),
    .val_5_i(first_stage_out_l[4]),
    .val_6_i(first_stage_out_l[5]),
    .val_7_i(first_stage_out_l[6]),
    .val_8_i(first_stage_out_l[7]),
    .val_9_i(first_stage_out_l[8]),
    .val_10_i(first_stage_out_l[9]),
    .val_11_i(first_stage_out_l[10]),
    .val_12_i(first_stage_out_l[11]),
    .val_13_i(first_stage_out_l[12]),
    .val_14_i(first_stage_out_l[13]),
    .val_15_i(first_stage_out_l[14]),
    .val_16_i(first_stage_out_l[15]),
    //Outputs
    .valid_o(second_stage_valid_l),
    .descend_o(second_stage_descend_l),
    .val_1_o(second_stage_out_l[0]),
    .val_2_o(second_stage_out_l[1]),
    .val_3_o(second_stage_out_l[2]),
    .val_4_o(second_stage_out_l[3]),
    .val_5_o(second_stage_out_l[4]),
    .val_6_o(second_stage_out_l[5]),
    .val_7_o(second_stage_out_l[6]),
    .val_8_o(second_stage_out_l[7]),
    .val_9_o(second_stage_out_l[8]),
    .val_10_o(second_stage_out_l[9]),
    .val_11_o(second_stage_out_l[10]),
    .val_12_o(second_stage_out_l[11]),
    .val_13_o(second_stage_out_l[12]),
    .val_14_o(second_stage_out_l[13]),
    .val_15_o(second_stage_out_l[14]),
    .val_16_o(second_stage_out_l[15])
);

 bitonic_sorter_third_stage third_stage (
    .clk_i(clk_i),
    .resetn_i(resetn_i),
    .descend_i(second_stage_descend_l),
    .valid_i(second_stage_valid_l),
    .val_1_i(second_stage_out_l[0]),
    .val_2_i(second_stage_out_l[1]),
    .val_3_i(second_stage_out_l[2]),
    .val_4_i(second_stage_out_l[3]),
    .val_5_i(second_stage_out_l[4]),
    .val_6_i(second_stage_out_l[5]),
    .val_7_i(second_stage_out_l[6]),
    .val_8_i(second_stage_out_l[7]),
    .val_9_i(second_stage_out_l[8]),
    .val_10_i(second_stage_out_l[9]),
    .val_11_i(second_stage_out_l[10]),
    .val_12_i(second_stage_out_l[11]),
    .val_13_i(second_stage_out_l[12]),
    .val_14_i(second_stage_out_l[13]),
    .val_15_i(second_stage_out_l[14]),
    .val_16_i(second_stage_out_l[15]),
    //Outputs
    .valid_o(third_stage_valid_l),
    .descend_o(third_stage_descend_l),
    .val_1_o(third_stage_out_l[0]),
    .val_2_o(third_stage_out_l[1]),
    .val_3_o(third_stage_out_l[2]),
    .val_4_o(third_stage_out_l[3]),
    .val_5_o(third_stage_out_l[4]),
    .val_6_o(third_stage_out_l[5]),
    .val_7_o(third_stage_out_l[6]),
    .val_8_o(third_stage_out_l[7]),
    .val_9_o(third_stage_out_l[8]),
    .val_10_o(third_stage_out_l[9]),
    .val_11_o(third_stage_out_l[10]),
    .val_12_o(third_stage_out_l[11]),
    .val_13_o(third_stage_out_l[12]),
    .val_14_o(third_stage_out_l[13]),
    .val_15_o(third_stage_out_l[14]),
    .val_16_o(third_stage_out_l[15])
);

bitonic_sorter_fourth_stage fourth_stage (
    .clk_i(clk_i),
    .resetn_i(resetn_i),
    .descend_i(third_stage_descend_l),
    .valid_i(third_stage_valid_l),
    .val_1_i(third_stage_out_l[0]),
    .val_2_i(third_stage_out_l[1]),
    .val_3_i(third_stage_out_l[2]),
    .val_4_i(third_stage_out_l[3]),
    .val_5_i(third_stage_out_l[4]),
    .val_6_i(third_stage_out_l[5]),
    .val_7_i(third_stage_out_l[6]),
    .val_8_i(third_stage_out_l[7]),
    .val_9_i(third_stage_out_l[8]),
    .val_10_i(third_stage_out_l[9]),
    .val_11_i(third_stage_out_l[10]),
    .val_12_i(third_stage_out_l[11]),
    .val_13_i(third_stage_out_l[12]),
    .val_14_i(third_stage_out_l[13]),
    .val_15_i(third_stage_out_l[14]),
    .val_16_i(third_stage_out_l[15]),
    //Outputs
    .valid_o(valid_o),
    .descend_o(descend_o),
    .val_1_o(val_1_o),
    .val_2_o(val_2_o),
    .val_3_o(val_3_o),
    .val_4_o(val_4_o),
    .val_5_o(val_5_o),
    .val_6_o(val_6_o),
    .val_7_o(val_7_o),
    .val_8_o(val_8_o),
    .val_9_o(val_9_o),
    .val_10_o(val_10_o),
    .val_11_o(val_11_o),
    .val_12_o(val_12_o),
    .val_13_o(val_13_o),
    .val_14_o(val_14_o),
    .val_15_o(val_15_o),
    .val_16_o(val_16_o)
);

endmodule
